### ISSUE TITLE
update error page to just show "something went wrong!"

### ISSUE THREAD

**Issue by gnomadic** [MetricsDAO/xyz#707]
Right now we're showing full strack traces if there's an error - we can hide those behind a user friendly error page because the stack traces should still go to sentry.

**Comment by A4x1** [comment]
Let me know how this works 
https://www.figma.com/file/xo32mL5Q9jRPVotbH6nv5h/MDAO-App-(Sandbox-%26-User-Testing)?node-id=6348%3A31369&t=IYzckA3UYB3Cwoco-1

**Comment by gnomadic** [comment]
hey that's awesome!  figure we can use it for other types of errors too besides just 404?

**Comment by A4x1** [comment]
> hey that's awesome! figure we can use it for other types of errors too besides just 404?

Got it. Made the change 👍

**Comment by gnomadic** [comment]
https://www.figma.com/file/xo32mL5Q9jRPVotbH6nv5h/MDAO-App-(Sandbox-%26-User-Testing)?node-id=6352-31137&t=1kRLLF4Qlck192wI-0

**Comment by thekakamora** [comment]
@gnomadic as the issue is closed, I'm assuming the fix has been deployed. With that assumption I forced an error by messing with the submission id in URL. I'm able to see stack traces.

![image](https://user-images.githubusercontent.com/86695148/234613662-8ca11285-6dda-4594-948d-6ec0bbb653fa.png)

**Comment by gnomadic** [comment]
hey yeah it's not fixed yet, this issue is open, in the priority lane - it should get into active development soon

**Comment by termaatFlipside** [comment]
@gnomadic / @A4x1 Do we want to give a link to the discord or anything like that?

**Comment by gnomadic** [comment]
Eh I don't think so, most of the errors are a 404 or one that can be recovered with a refresh.
